name: Build fat jar, native and docker on master branch with Gradle

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Clone sub repos
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        git submodule init
        git submodule update
    - name: Print env
      run: echo $GITHUB_ACTOR
    - name: Build shadowJar and native binary with Gradle
      run: ./gradlew generateManpageAsciiDoc shadowJar nativeCompile docker -Dorg.gradle.daemon=false
